name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Check coding style
        run: vendor/bin/pint --test

  analysis:
    name: Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Analyse code
        run: vendor/bin/phpstan

  tests:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.2"
        dependency-versions:
          - "lowest"
          - "highest"

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependency-versions }}

      - name: Install Xdebug
        run: sudo apt-get install -y php-xdebug

      - name: Enable Xdebug
        run: echo 'zend_extension=xdebug.so' | sudo tee -a /etc/php/$(php -r 'echo PHP_MAJOR_VERSION . "." . PHP_MINOR_VERSION;')/cli/conf.d/20-xdebug.ini

      - name: Run tests with coverage
        run: vendor/bin/pest --coverage --min=100
